development:
  # ruby vendor/plugins/sanger_authentication/auth_server.rb -p 3002
  # remeber to unset local http_proxy environment variable
  sanger_auth_service: http://localhost:3002/verify_login
  sanger_login_service: http://localhost:3002/LOGIN
  proxy: ""

authentication_service: &AUTHENTICATION_SERVICE
  sanger_auth_service: https://intweb.sanger.ac.uk/cgi-bin/utils/verify_login
  sanger_login_service: https://enigma.sanger.ac.uk/LOGIN

web_proxy: &WEB_PROXY
  proxy: http://wwwcache.sanger.ac.uk:3128

test:
  <<: *AUTHENTICATION_SERVICE
  <<: *WEB_PROXY
 
staging:
  <<: *AUTHENTICATION_SERVICE
  <<: *WEB_PROXY
 
training:
  <<: *AUTHENTICATION_SERVICE
  <<: *WEB_PROXY

production:
  <<: *AUTHENTICATION_SERVICE
  <<: *WEB_PROXY
